import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET,
  DISCORD_GUILD_ID,
  DISCORD_REDIRECT_URI,
  DISCORD_STAFF_ROLE,
  DISCORD_DEFAULT_ROLE,
  DISCORD_MOD_LOGS,
  DISCORD_LOG_WEBHOOK_URL,
  DISCORD_APPALCART_WEBHOOK,
  MYSQL_HOST,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_DB,
  PORT,
  JWT_SECRET,
} = process.env;

// Required environment variables check
if (
  !DISCORD_TOKEN ||
  !DISCORD_CLIENT_ID ||
  !DISCORD_CLIENT_SECRET ||
  !DISCORD_GUILD_ID ||
  !DISCORD_REDIRECT_URI ||
  !DISCORD_STAFF_ROLE ||
  !DISCORD_DEFAULT_ROLE ||
  !DISCORD_MOD_LOGS ||
  !DISCORD_LOG_WEBHOOK_URL ||
  !DISCORD_APPALCART_WEBHOOK ||
  !MYSQL_HOST ||
  !MYSQL_USERNAME ||
  !MYSQL_PASSWORD ||
  !MYSQL_DB ||
  !PORT ||
  !JWT_SECRET
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET,
  DISCORD_GUILD_ID,
  DISCORD_REDIRECT_URI,
  DISCORD_STAFF_ROLE,
  DISCORD_DEFAULT_ROLE,
  DISCORD_MOD_LOGS,
  DISCORD_LOG_WEBHOOK_URL,
  DISCORD_APPALCART_WEBHOOK,
  MYSQL: {
    HOST: MYSQL_HOST,
    USERNAME: MYSQL_USERNAME,
    PASSWORD: MYSQL_PASSWORD,
    DB: MYSQL_DB,
  },
  PORT: Number(PORT),
  JWT_SECRET,
};