import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  DISCORD_STAFF_ROLE,
  DISCORD_DEFAULT_ROLE,
  DISCORD_MOD_LOGS,
  DISCORD_LOG_WEBHOOK_URL,
  DISCORD_APPALCART_WEBHOOK,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !DISCORD_CLIENT_ID ||
  !DISCORD_GUILD_ID ||
  !DISCORD_LOG_WEBHOOK_URL ||
  !DISCORD_APPALCART_WEBHOOK ||
  !DISCORD_STAFF_ROLE ||
  !DISCORD_DEFAULT_ROLE ||
  !DISCORD_MOD_LOGS
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  DISCORD_LOG_WEBHOOK_URL,
  DISCORD_STAFF_ROLE,
  DISCORD_DEFAULT_ROLE,
  DISCORD_MOD_LOGS,
  DISCORD_APPALCART_WEBHOOK,
};
