import dotenv from "dotenv";

dotenv.config();
/**
 * DISCORD_TOKEN=
DISCORD_CLIENT_ID=
DISCORD_GUILD_ID=
DISCORD_STAFF_ROLE=
DISCORD_DEFAULT_ROLE=
DISCORD_MOD_LOGS=
DISCORD_LOG_WEBHOOK_URL=https://discord.com/api/webhooks/
DISCORD_APPALCART_WEBHOOK=
MYSQL_HOST=127.0.0.1
MYSQL_USERNAME=yosef
MYSQL_PASSWORD=
MYSQL_DB=yosef
 */

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  DISCORD_STAFF_ROLE,
  DISCORD_DEFAULT_ROLE,
  DISCORD_MOD_LOGS,
  DISCORD_LOG_WEBHOOK_URL,
  DISCORD_APPALCART_WEBHOOK,
  MYSQL_HOST,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_DB,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !DISCORD_CLIENT_ID ||
  !DISCORD_GUILD_ID ||
  !DISCORD_LOG_WEBHOOK_URL ||
  !DISCORD_APPALCART_WEBHOOK ||
  !DISCORD_STAFF_ROLE ||
  !DISCORD_DEFAULT_ROLE ||
  !DISCORD_MOD_LOGS ||
  !MYSQL_HOST ||
  !MYSQL_USERNAME ||
  !MYSQL_PASSWORD ||
  !MYSQL_DB
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  DISCORD_LOG_WEBHOOK_URL,
  DISCORD_STAFF_ROLE,
  DISCORD_DEFAULT_ROLE,
  DISCORD_MOD_LOGS,
  DISCORD_APPALCART_WEBHOOK,
  MYSQL_HOST,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_DB,
};
